version: '3.4'
services:
#  Optional
#  afresco-countries-share:
#    image: ${docker.share.image}:${alfresco.share.version}
#    environment:
#      REPO_HOST: afresco-countries-acs
#      REPO_PORT: 8080
#    ports:
#      - "${share.port}:8080"
  afresco-countries-acs:
    image: alfresco-content-services-afresco-countries:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
    ports:
      - "${acs.port}:8080"
      - "${acs.debug.port}:8888"
    volumes:
      - afresco-countries-acs-volume:/usr/local/tomcat/alf_data
    depends_on:
      - afresco-countries-postgres
  afresco-countries-postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "${postgres.port}:5432"
    volumes:
      - afresco-countries-db-volume:/var/lib/postgresql/data
  afresco-countries-ass:
    image: alfresco/alfresco-search-services:1.2.0
    environment:
      SOLR_ALFRESCO_HOST: afresco-countries-acs
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: afresco-countries-ass
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
    ports:
      - "8983:8983"
    volumes:
      - afresco-countries-ass-volume:/opt/alfresco-search-services/contentstore
      - afresco-countries-ass-volume:/opt/alfresco-search-services/data
volumes:
  afresco-countries-acs-volume:
    external: true
  afresco-countries-db-volume:
    external: true
  afresco-countries-ass-volume:
    external: true